/// Maps to PostgreSQL schema: members (church congregation table)
class Member {
  final String id;
  final String firstName;
  final String lastName;
  final String? email;
  final String phone;
  final DateTime? dateOfBirth;
  final String? gender; // male, female
  final String? address;
  final String? ministry; // youth, choir, ushering, children, media, womens_guild, mens_fellowship
  final String membershipStatus; // active, inactive, visitor, new_convert, transferred
  final String? maritalStatus; // single, married, widowed, divorced
  final String? occupation;
  final String? emergencyContactName;
  final String? emergencyContactPhone;
  final DateTime? joinedDate;
  final bool isBaptized;
  final DateTime? baptizedDate;
  final String? avatarUrl;
  final String? notes;
  final DateTime createdAt;
  final DateTime? updatedAt;

  const Member({
    required this.id,
    required this.firstName,
    required this.lastName,
    this.email,
    required this.phone,
    this.dateOfBirth,
    this.gender,
    this.address,
    this.ministry,
    this.membershipStatus = 'active',
    this.maritalStatus,
    this.occupation,
    this.emergencyContactName,
    this.emergencyContactPhone,
    this.joinedDate,
    this.isBaptized = false,
    this.baptizedDate,
    this.avatarUrl,
    this.notes,
    required this.createdAt,
    this.updatedAt,
  });

  /// Computed full name
  String get fullName => '$firstName $lastName'.trim();

  /// Avatar initials
  String get initials {
    return '${firstName.isNotEmpty ? firstName[0] : ''}'
            '${lastName.isNotEmpty ? lastName[0] : ''}'
        .toUpperCase();
  }

  /// Display-friendly ministry name
  String? get ministryLabel {
    if (ministry == null) return null;
    return ministry!.split('_').map((w) => w[0].toUpperCase() + w.substring(1)).join(' ');
  }

  /// Display-friendly status
  String get statusLabel {
    return membershipStatus.split('_').map((w) => w[0].toUpperCase() + w.substring(1)).join(' ');
  }

  /// Age calculation
  int? get age {
    if (dateOfBirth == null) return null;
    final now = DateTime.now();
    int age = now.year - dateOfBirth!.year;
    if (now.month < dateOfBirth!.month ||
        (now.month == dateOfBirth!.month && now.day < dateOfBirth!.day)) {
      age--;
    }
    return age;
  }

  /// How long they've been a member
  String get tenure {
    if (joinedDate == null) return 'Unknown';
    final now = DateTime.now();
    final diff = now.difference(joinedDate!);
    final years = (diff.inDays / 365).floor();
    final months = ((diff.inDays % 365) / 30).floor();

    if (years > 0) return '${years}yr${years > 1 ? 's' : ''}';
    if (months > 0) return '${months}mo';
    return '${diff.inDays}d';
  }

  factory Member.fromJson(Map<String, dynamic> json) {
    return Member(
      id: json['id'].toString(),
      firstName: json['first_name'] ?? '',
      lastName: json['last_name'] ?? '',
      email: json['email'],
      phone: json['phone'] ?? '',
      dateOfBirth: _parseDateNullable(json['date_of_birth']),
      gender: json['gender'],
      address: json['address'],
      ministry: json['ministry'] ?? json['department'],
      membershipStatus: json['membership_status'] ?? 'active',
      maritalStatus: json['marital_status'],
      occupation: json['occupation'],
      emergencyContactName: json['emergency_contact_name'],
      emergencyContactPhone: json['emergency_contact_phone'],
      joinedDate: _parseDateNullable(json['joined_date']),
      isBaptized: json['is_baptized'] ?? false,
      baptizedDate: _parseDateNullable(json['baptized_date']),
      avatarUrl: json['avatar_url'],
      notes: json['notes'],
      createdAt: _parseDate(json['created_at']),
      updatedAt: _parseDateNullable(json['updated_at']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'first_name': firstName,
      'last_name': lastName,
      'email': email,
      'phone': phone,
      'date_of_birth': dateOfBirth?.toIso8601String(),
      'gender': gender,
      'address': address,
      'ministry': ministry,
      'membership_status': membershipStatus,
      'marital_status': maritalStatus,
      'occupation': occupation,
      'emergency_contact_name': emergencyContactName,
      'emergency_contact_phone': emergencyContactPhone,
      'joined_date': joinedDate?.toIso8601String(),
      'is_baptized': isBaptized,
      'baptized_date': baptizedDate?.toIso8601String(),
      'avatar_url': avatarUrl,
      'notes': notes,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }

  /// For creating a new member (id and timestamps generated by backend)
  Map<String, dynamic> toCreateJson() {
    final json = toJson();
    json.remove('id');
    json.remove('created_at');
    json.remove('updated_at');
    return json;
  }

  Member copyWith({
    String? id,
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
    DateTime? dateOfBirth,
    String? gender,
    String? address,
    String? ministry,
    String? membershipStatus,
    String? maritalStatus,
    String? occupation,
    String? emergencyContactName,
    String? emergencyContactPhone,
    DateTime? joinedDate,
    bool? isBaptized,
    DateTime? baptizedDate,
    String? avatarUrl,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Member(
      id: id ?? this.id,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      gender: gender ?? this.gender,
      address: address ?? this.address,
      ministry: ministry ?? this.ministry,
      membershipStatus: membershipStatus ?? this.membershipStatus,
      maritalStatus: maritalStatus ?? this.maritalStatus,
      occupation: occupation ?? this.occupation,
      emergencyContactName: emergencyContactName ?? this.emergencyContactName,
      emergencyContactPhone: emergencyContactPhone ?? this.emergencyContactPhone,
      joinedDate: joinedDate ?? this.joinedDate,
      isBaptized: isBaptized ?? this.isBaptized,
      baptizedDate: baptizedDate ?? this.baptizedDate,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() => 'Member(id: $id, name: $fullName, status: $membershipStatus)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Member && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  static DateTime _parseDate(dynamic value) {
    if (value == null) return DateTime.now();
    if (value is DateTime) return value;
    return DateTime.parse(value.toString());
  }

  static DateTime? _parseDateNullable(dynamic value) {
    if (value == null) return null;
    if (value is DateTime) return value;
    return DateTime.parse(value.toString());
  }
}

